text_generation:
  en:
    adapter: "berlayar.adapters.models.gpt4.GPT4Adapter"
    model_name: "gpt-4-1106-preview"
    params:
      temperature: 0.7
      frequency_penalty: 0.0
      presence_penalty: 0.0
      system_message: "You are a helpful assistant."
    api_key_env: "OPENAI_API_KEY"
  zh:
    adapter: "berlayar.adapters.models.kimi.KimiAdapter"  # Assuming similar path update for KimiAdapter
    model_name: "moonshot-v1-32k"
    params:
      temperature: 0.7
      frequency_penalty: 0.0
      presence_penalty: 0.0
      system_message: "你是 Kimi，由 Moonshot AI 提供的人工智能助手，你更擅长中文和英文的对话。你会为用户提供安全，有帮助，准确的回答。同时，你会拒绝一切涉及恐怖主义，种族歧视，黄色暴力等问题的回答。Moonshot AI 为专有名词，不可翻译成其他语言。"
    api_key_env: "KIMI_API_KEY"
    base_url: "https://api.moonshot.cn/v1"

image_generation:
  en:
    adapter: "berlayar.adapters.models.dalle3.DalleAdapter"  # Updated path
    model_name: "dall-e-3"
    n: 1
    size: "1024x1024"
    api_key_env: "OPENAI_API_KEY"

audio_generation:
  en:
    adapter: "berlayar.adapters.models.elevenlabs.ElevenLabsAdapter"  # Updated path
    url: "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}/stream"
    model_id: "eleven_multilingual_v2"
    voice_id: "0M23V8kIecNGWiNzhRRn"
    api_key_env: "ELEVENLABS_API_KEY"
  zh:
    adapter: "berlayar.adapters.models.elevenlabs.ElevenLabsAdapter"  # Updated path
    url: "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}/stream"
    model_id: "eleven_multilingual_v2"
    voice_id: "your_mandarin_voice_id"
    api_key_env: "ELEVENLABS_API_KEY"
